Repository SuitestAutomation/suitest-js-api, pull requests merged in 2018-06, with the labels that each got.

#63 SUIT-9466 Add interactive test progress handler
  lib/api/webSockets.js
  lib/texts.js
  lib/utils/interactiveProgressHanlder.js
  lib/utils/testHelpers/mockWebSocket.js
  test/utils/interactiveProgressHanlder.test.js
Labels: enhancement

#70 SUIT-9581 - Fix bug when checking on element props in .until would cause TypeError
  lib/utils/socketChainHelper.js
Labels: bug

#75 Feature/suit 9119 Update JS API configuration unification
  config/index.js
  lib/constants/enviroment.js
  lib/mappings.js
  lib/testLauncher/SuitestLauncher.js
  lib/testLauncher/commands/automated.js
  lib/testLauncher/commands/interactive.js
  lib/testLauncher/processArgs.js
  lib/utils/testLauncherHelper.js
  package.json
  test/utils/testLauncherHelper.test.js
  yarn.lock
Labels: bug, enhancement

#73 SUIT-9651 - Fix bug when WebStorm wouldn't close Node's child process while debugging
  index.js
  lib/testLauncher/SuitestLauncher.js
  lib/testLauncher/index.js
  lib/testLauncher/processReaper.js
Labels: enhancement

#76 SUIT-9282 - Improve logger output format
  lib/utils/logger.js
Labels: enhancement
